# Re-usable stage template to deploy Infrastructure on QA, UAT, Prod environments

parameters:
  environmentName: ''
  environmentServiceName: ''
  remoteStateContainerName: ''
  remoteStateResourceGroup: ''
  remoteStateServiceConnection: ''
  remoteStateStorageName: ''
  shouldRunAzLogin: ''
  terraformCommandOptions: ''
  terraformWorkingDirectory: ''

stages:
  - stage: deploy_${{ parameters.environmentName }}_infrastructure
    displayName: 'Deploy ${{ parameters.environmentName }} infra'
    jobs:            
      - template: /.azdo/jobs/deploy-Infrastructure.yaml
        parameters: 
          environmentServiceName: '${{ parameters.environmentServiceName }}'
          shouldRunAzLogin: '${{ parameters.shouldRunAzLogin }}'
          remoteStateContainerName: '${{ parameters.remoteStateContainerName }}'
          remoteStateFileName: '${{ parameters.environmentName }}.tfstate' 
          remoteStateResourceGroup: '${{ parameters.remoteStateResourceGroup }}'
          remoteStateServiceConnection: '${{ parameters.remoteStateServiceConnection }}'
          remoteStateStorageName: '${{ parameters.remoteStateStorageName }}'
          terraformWorkingDirectory: '${{ parameters.terraformWorkingDirectory }}'
          terraformCommandOptions: '${{ parameters.terraformCommandOptions }}'